# 4.1 Exercise on Functions:
# Task - 1:
# Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def length_convert(value, unit):
    # meter and feet
    if unit == "m":
        return value * 3.28084, "ft"
    elif unit == "ft":
        return value / 3.28084, "m"
    else:
        raise ValueError("Invalid unit for length conversion")

def weight_convert(value, unit):
    # kg and pound
    if unit == "kg":
        return value * 2.20, "lbs"
    elif unit == "lbs":
        return value / 2.20, "kg"
    else:
        raise ValueError("Invalid unit for weight conversion")

def volume_convert(value, unit):
    # liters and gallons
    if unit == "L":
        return value * 0.264172, "gal"
    elif unit == "gal":
        return value / 0.264172, "L"
    else:
        raise ValueError("Invalid unit for volume conversion")

def main():
    print("Unit Converter")
    print("Select conversion type:")
    print("1. Convert Length (m <-> ft)")
    print("2. Convert Weight (kg <-> lbs)")
    print("3. Convert Volume (L <-> gal)")

    try:
        choice = int(input("Enter choice (1-3): "))
        value = float(input("Enter value to convert: "))

        if choice == 1:
            from_unit = input("Enter unit (m/ft): ").strip().lower()
            result = length_convert(value, from_unit)
        elif choice == 2:
            from_unit = input("Enter unit (kg/lbs): ").strip().lower()
            result = weight_convert(value, from_unit)
        elif choice == 3:
            from_unit = input("Enter unit (L/gal): ").strip().lower()
            result = volume_convert(value, from_unit)
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
            return

        print(f"Converted value: {result[0]:.2f} {result[1]}")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Unit Converter
Select conversion type:
1. Convert Length (m <-> ft)
2. Convert Weight (kg <-> lbs)
3. Convert Volume (L <-> gal)
Enter choice (1-3): 1
Enter value to convert: 10
Enter unit (m/ft): ft
Converted value: 3.05 m


# Task - 2:
# Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(num):
    """Returns the sum of a list of numbers."""
    return sum(num)

def calculate_avarage(num):
    """Returns the average of a list of numbers."""
    return sum(num)/len(num) if num else 0

def calculate_max(num):
    """Returns the maximum value from a list of numbers."""
    return max(num)

def calculate_min(num):
   """Returns the minimum value from a list of numbers."""
   return min(num)
def main():
  print("Choose an operation:")
  print("1. Sum")
  print("2. Average")
  print("3. Maximum")
  print("4. Minimum")

  try:
    choice = int(input("Enter choice (1/2/3/4): "))
    numbers = input("Enter a list of numbers separated by spaces: ").split()

    """converting input string to list of numbers"""
    num = [float(num) for num in numbers]

    if not num:
      print("The list is empty.")
      return

    if choice == 1:
      print("Sum:", calculate_sum(num))
    elif choice == 2:
      print("Average:", calculate_avarage(num))
    elif choice == 3:
      print("Maximum:", calculate_max(num))
      result = calculate_sum(num)
    elif choice == 4:
      print("Minimum:", calculate_min(num))
    else:
      print("Invalid choice. Please select 1, 2, or 3.")
      return
  except ValueError:
    print("Invalid input. Please enter a list of numbers separated by spaces.")
  except Exception as e:
    print(f"An error occurred: {e}")

if __name__ == "__main__":
  main()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1/2/3/4): 2
Enter a list of numbers separated by spaces: 1 2 3 4 5
Average: 3.0


# 1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def every_other_element(lst):
  """Extracts every other element from the given list, starting from the first element"""
  return lst[::2]

def main():
  """Taking user input"""
  user_input = input("Enter list of numbers seperated by spaces:")

  """Converting input string into list of int"""
  input_list = [int(x) for x in user_input.split()]

  result = every_other_element(input_list)
  print("Every other element: ", result)

if __name__ == "__main__":
    main()

Enter list of numbers seperated by spaces:1
Every other element:  [1]


In [ ]:
def get_sublist(lst, start, end):
  """Returns a sublist from the given list starting from 'start' to 'end' (inclusive)"""
  return lst[start:end+1]

def main():
    """Taking user input"""
    user_input = input("Enter list of numbers seperated by spaces:")

    try:
      """Converting input string into list of int"""
      input_list = [int(x) for x in user_input.split()]
    except ValueError:
      print("Invalid input. Please enter a list of numbers seperated by spaces.")
      return

    if not input_list:
      print("The list is empty.")
      return
    try:
      """User uinput for start and end index"""
      start = int(input("Eneter the start index"))
      end = int(input("Enter the end index"))

      if start<0 or end<0:
        raise ValueError("Entered value must be non negative")

      if start > len(input_list) - 1 or end > len(input_list) - 1:
        raise IndexError("Index out of range")

      result = get_sublist(input_list, start, end)
      print("Sublist: ", result)

    except (ValueError, IndexError) as e:
      print(f"Error: {e}")

if __name__ == "__main__":
  main()



Enter list of numbers seperated by spaces:9 8 7 6 5 4 3 2 1
Eneter the start index1
Enter the end index5
Sublist:  [8, 7, 6, 5, 4]


# 2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

# 3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
  return lst[::-1]

def main():
    """Taking user input"""
    user_input = input("Enter list of numbers seperated by spaces:")

    try:
      """Converting input string into list of int"""
      input_list = [int(x) for x in user_input.split()]
    except ValueError:
      print("Invalid input. Please enter a list of numbers seperated by spaces.")
      return

    if not input_list:
      print("The list is empty.")
      return

    reverse_lict = reverse_list(input_list)
    print("Reversed list: ", reverse_lict)

if __name__ == "__main__":
  main()

Enter list of numbers seperated by spaces:9 8 7 6 5 4
Reversed list:  [4, 5, 6, 7, 8, 9]


# 4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_element_first_last(lst):
  return lst[1:-1]

def main():
    """Taking user input"""
    user_input = input("Enter list of numbers seperated by spaces:")

    try:
      """Converting input string into list of int"""
      input_list = [int(x) for x in user_input.split()]
    except ValueError:
      print("Invalid input. Please enter a list of numbers seperated by spaces.")
      return

    if not input_list:
      print("The list is empty.")
      return

    if len(input_list)<3:
      print("Must contain at least 3 elements")
      return

    result_list = remove_element_first_last(input_list)
    print("Resulting list: ", result_list)

if __name__ == "__main__":
  main()

Enter list of numbers seperated by spaces:5
Must contain at least 3 elements


# 5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """Returns the first n elements of the given list using slicing."""
    return lst[:n]

def main():
    """Taking user input"""
    user_input = input("Enter a list of numbers separated by spaces: ")

    try:
        # Converting input string into list of integers
        input_list = [int(x) for x in user_input.split()]
    except ValueError:
        print("Invalid input. Please enter a list of numbers separated by spaces.")
        return

    if not input_list:
        print("The list is empty.")
        return

    try:
        n = int(input("Enter the number of elements to extract from the list: "))

        if n < 0:
            print("The number of elements must be non-negative.")
            return

        if n > len(input_list):
            print("The number of elements exceeds the length of the list.")
            return

        # Corrected function call
        result_list = get_first_n(input_list, n)
        print(f"The first {n} elements are: {result_list}")

    except ValueError:
        print("Invalid input. Please enter a valid integer for 'n'.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 5
Enter the number of elements to extract from the list: 2
The number of elements exceeds the length of the list.


# 6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
  return lst[-n:]

def main():
    """Taking user input"""
    user_input = input("Enter a list of numbers separated by spaces: ")

    try:
        # Converting input string into list of integers
        input_list = [int(x) for x in user_input.split()]
    except ValueError:
        print("Invalid input. Please enter a list of numbers separated by spaces.")
        return

    if not input_list:
        print("The list is empty.")
        return

    try:
        n = int(input("Enter the number of elements to extract from the end of the list: "))

        if n < 0:
            print("The number of elements must be non-negative.")
            return
        if n > len(input_list):
            print("The number of elements exceeds the length of the list.")
            return

        result_list = get_last_n(input_list, n)
        print(f"The last {n} elements are: {result_list}")

    except ValueError:
        print("Invalid input. Please enter a valid integer for 'n'.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 6
Enter the number of elements to extract from the end of the list: 5
The number of elements exceeds the length of the list.


# 7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
  """Returns a list containing every second element starting from the second-to-last, moving backward."""
  return lst[-2::-2]

def main():
    """Taking user input"""
    user_input = input("Enter a list of numbers separated by spaces: ")

    try:
        # Converting input string into list of integers
        input_list = [int(x) for x in user_input.split()]
    except ValueError:
        print("Invalid input. Please enter a list of numbers separated by spaces.")
        return

    if not input_list:
        print("The list is empty.")
        return
    result_list = reverse_skip(input_list)
    print("Resulting list: ", result_list)

if __name__ == "__main__":
    main()



Enter a list of numbers separated by spaces: 1
Resulting list:  []


# 1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
import ast
def flatten(lst):
  flatten_list = []

  for item in lst:
    if isinstance(item, list):
      # Recursively flatten the nested list
      flatten_list.extend(flatten(item))
    else:
      # Adding non-list item to the flat list
      flatten_list.append(item)

  return flatten_list

def main():
  user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")

  try:
      #converting into python list using ast.literal_eval
      input_list = ast.literal_eval(user_input)

      if not isinstance(input_list, list):
        print("Invalid input. Please enter a valid nested list.")
        return

      flattened_list = flatten(input_list)
      print("Flattened list: ", flattened_list)

  except ValueError:
      print("Invalid input. Please enter a valid nested list.")

if __name__ == "__main__":
  main()


Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): 1
Invalid input. Please enter a valid nested list.


# 2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
import ast

def access_nested_element(lst, indices):
  """Returns the element at the specified indices in the nested list."""
  try:
    for index in indices:
      lst = lst[index]
    return lst
  except IndexError:
    print("Invalid indices. Please provide valid indices.")

def main():
  lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
  indices = [1, 2]

  result = access_nested_element(lst, indices)
  print("Result: ", result)

if __name__ == "__main__":
  main()

Result:  6


# 3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
  total = 0

  for item in lst:
    if isinstance(item, list):
      # Recursively calculate the sum of nested lists
      total += sum_nested(item)
    else:
      # Adding non-list item to the total
      total += item

  return total

def main():
  lst = [[1, 2], [3, [4, 5]], 6]
  result = sum_nested(lst)
  print(f"Sum: {result}")

if __name__ == "__main__":
  main()

Sum: 21


# 4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    new_lst = []
    for item in lst:
        if isinstance(item, list):
            #Recursively remove the element from sublist
            modified_sublist = remove_element(item, elem)
            if modified_sublist:
                new_lst.append(modified_sublist)
        else:
            if item != elem:  #Adding item if it's not the element to remove
                new_lst.append(item)
    return new_lst

def main():
    lst = [[1, 2], [3, 2], [4, 5]]
    elem = 2
    result = remove_element(lst, elem)
    print(f"Modified list after removing all occurrences of {elem} is: {result}")

if __name__ == "__main__":
    main()


Modified list after removing all occurrences of 2 is: [[1], [3], [4, 5]]


# 5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    max_value = float('-inf')  # Start with negative infinity

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursively find max in sublist
        else:
            max_value = max(max_value, item)  # Compare current item to max_value

    return max_value

def main():
    lst = [[1, 2], [3, [4, 5]], 6]
    result = find_max(lst)
    print(f"Maximum element: {result}")

if __name__ == "__main__":
    main()


Maximum element: 6


# 6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """Counts the occurrences of 'elem' in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            # Recursively count occurrences in the sublist
            count += count_occurrences(item, elem)
        else:
            # Count occurrences in the current element
            if item == elem:
                count += 1
    return count

def main():
    lst = [[1, 1], [2, 3], [2, 4]]
    elem = 1
    result = count_occurrences(lst, elem)
    print(f"The element {elem} appears {result} times in nested list.")

if __name__ == "__main__":
    main()
""

The element 1 appears 2 times in nested list.


''

# 7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            # Recursively flatten the sublist
            flat_list.extend(deep_flatten(item))
        else:
            # Add non-list elements directly to the flat list
            flat_list.append(item)
    return flat_list

def main():
    lst = [[[9, 8], [7, 6]], [[5, 4], [3, 2]]]
    result = deep_flatten(lst)
    print(f"Flattened list: {result}")

if __name__ == "__main__":
    main()


Flattened list: [9, 8, 7, 6, 5, 4, 3, 2]


# 8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    flat_list = [] #flatten nested list

    def flatten(lst):
        for item in lst:
            if isinstance(item, list):
                flatten(item)  # Recursively flatten sublists
            else:
                flat_list.append(item)  # Add non-list elements to the flat list

    flatten(lst)
    if flat_list:
        total_sum = sum(flat_list)
        total_count = len(flat_list)
        return total_sum / total_count
    else:
        return 0  # If the list is empty, return 0

def main():
    lst =[[[9, 8], [7, 6]], [[5, 4], [3, 2]]]
    result = average_nested(lst)
    print(f"The average of all elements is: {result}")

if __name__ == "__main__":
    main()


The average of all elements is: 5.5


# 10 To - Do - NumPy
# 10.1 Basic Vector and Matrix Operation with Numpy.
# Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
def initialize_empty_array():
    arr = np.empty((2, 2))
    print("Empty array with size 2x2:\n", arr)

def initialize_all_one_array():
    arr = np.ones((4, 2))
    print("All ones array with size 4x2:\n", arr)

def create_array_with_fill_value(fill_value):
    arr = np.full((3, 3), fill_value)
    print(f"Array filled with {fill_value}:\n", arr)

def create_array_of_zeros_like(reference_array):
    arr = np.zeros_like(reference_array)
    print(f"New array of zeros with same shape as reference array:\n", arr)

def create_array_of_ones_like(reference_array):
    arr = np.ones_like(reference_array)
    print(f"New array of ones with same shape as reference array:\n", arr)

def convert_list_to_numpy_array(new_list):
    arr = np.array(new_list)
    print(f"List converted to numpy array:\n", arr)

def main():
    initialize_empty_array()
    initialize_all_one_array()
    create_array_with_fill_value(7)  #Filled with value 7
    reference_array = np.array([[1, 2, 3], [4, 5, 6]])
    create_array_of_zeros_like(reference_array)
    create_array_of_ones_like(reference_array)
    new_list = [1, 2, 3, 4]
    convert_list_to_numpy_array(new_list)

if __name__ == "__main__":
    main()


Empty array with size 2x2:
 [[6.76383632e-310 1.78961249e-316]
 [6.91750406e-315 1.56645200e-305]]
All ones array with size 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
New array of zeros with same shape as reference array:
 [[0 0 0]
 [0 0 0]]
New array of ones with same shape as reference array:
 [[1 1 1]
 [1 1 1]]
List converted to numpy array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
def create_range_array():
    arr = np.arange(10, 50)
    print("Array with values from 10 to 49:\n", arr)

create_range_array()

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
def create_3x3_matrix():
    arr = np.arange(9).reshape(3, 3)
    print("3X3 matrix with values from 0 to 8:\n", arr)

create_3x3_matrix()

In [ ]:
def create_identity_matrix():
    arr = np.eye(3)
    print("3X3 Identity matrix:\n", arr)

create_identity_matrix()

3X3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
def create_random_10x10_and_min_max():
    arr = np.random.random((10, 10))
    min_value = arr.min()
    max_value = arr.max()
    print("Random 10X10 array:\n", arr)
    print("Min value:", min_value)
    print("Max value:", max_value)

create_random_10x10_and_min_max()

Random 10X10 array:
 [[0.07505641 0.52363304 0.14745547 0.17179321 0.32112001 0.91930395
  0.6653879  0.20384853 0.94937394 0.82290946]
 [0.5655427  0.96432049 0.00217923 0.18891774 0.34791024 0.4487667
  0.66567324 0.97923575 0.94001294 0.10065969]
 [0.0595643  0.90527901 0.0965544  0.91005141 0.48116534 0.53438686
  0.08034166 0.63999455 0.8022795  0.28455412]
 [0.23033861 0.15932711 0.55261968 0.98362206 0.05839524 0.61975044
  0.52498577 0.10373853 0.38135499 0.3428551 ]
 [0.20970674 0.91417418 0.9260939  0.87158537 0.46407991 0.92587387
  0.74322863 0.67552115 0.15828999 0.44630988]
 [0.65918857 0.78087554 0.26020936 0.72050177 0.5146895  0.32088209
  0.03502369 0.5653203  0.47995734 0.62887444]
 [0.87199358 0.04162083 0.36681968 0.70114644 0.85444505 0.49924472
  0.39669053 0.17818053 0.38467107 0.7434521 ]
 [0.09873948 0.45699906 0.56230744 0.72016762 0.2479001  0.21739424
  0.58311383 0.9384235  0.0603827  0.66720234]
 [0.43252952 0.11536044 0.68588695 0.07876136 0.73927708 0.0

In [ ]:
def modify_zero_array():
    arr = np.zeros(10)
    arr[4] = 1
    print("Array with 5th element replaced by 1:\n", arr)

modify_zero_array()

Array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
def reverse_array():
    arr = np.array([1, 2, 0, 0, 4, 0])
    reversed_arr = arr[::-1]
    print("Reversed array:\n", reversed_arr)

reverse_array()

Reversed array:
 [0 4 0 0 2 1]


In [ ]:
def create_border_array():
    arr = np.ones((5, 5))
    arr[1:-1, 1:-1] = 0
    print("", arr)

create_border_array()

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
def create_checkerboard():
    arr = np.zeros((8, 8), dtype=int)
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    print("", arr)

create_checkerboard()

 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

def add_arrays():
    result = x + y
    print("Addition of x and y:\n", result)

def subtract_arrays():
    result = x - y
    print("Subtraction of x and y:\n", result)

def multiply_array():
    num = 2
    result = x * num
    print(f"Multiplying x by {num}:\n", result)

def square_elements():
    result = np.square(x)
    print("Square of each element of x:\n", result)

def dot_product():
    # Dot product of v and w
    result_vw = np.dot(v, w)
    # Dot product of x and v
    result_xv = np.dot(x, v)
    # Dot product of x and y
    result_xy = np.dot(x, y)

    print(f"Dot product of v and w: {result_vw}")
    print(f"Dot product of x and v: \n{result_xv}")
    print(f"Dot product of x and y: \n{result_xy}")


def concatenate_arrays():
    # Concatenate x and y along rows (axis 0)
    result_xy_rows = np.concatenate((x, y), axis=0)
    print("Concatenation of x and y along rows:\n", result_xy_rows)

    # Concatenate v and w along columns (axis 1)
    v_reshaped = v.reshape(-1, 1)  # Reshape v to column vector
    w_reshaped = w.reshape(-1, 1)  # Reshape w to column vector
    result_vw_columns = np.concatenate((v_reshaped, w_reshaped), axis=1)
    print("Concatenation of v and w along columns:\n", result_vw_columns)

def main():
    add_arrays()
    subtract_arrays()
    multiply_array()
    square_elements()
    dot_product()
    concatenate_arrays()

if __name__ == "__main__":
  main()


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplying x by 2:
 [[ 2  4]
 [ 6 10]]
Square of each element of x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v: 
[29 77]
Dot product of x and y: 
[[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]


In [ ]:
def concatenate_xv():
    try:
        result_xv = np.concatenate((x, v), axis=1)
        print("Concatenation of x and v along columns:\n", result_xv)
    except ValueError as e:
        print(f"Error occurred: {e}")

def main():
    concatenate_xv()

if __name__ == "__main__":
    main()

Error occurred: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

def prove_A_inv():
  A_inv = np.linalg.inv(A)

  identity_matrix = np.dot(A, A_inv)
  print("A * A^-1 (Identity Matrix):\n", identity_matrix)

def prove_AB_not_equal_BA():
    AB = np.dot(A, B)
    BA = np.dot(B, A)
    print("AB:\n", AB)
    print("BA:\n", BA)
    if np.array_equal(AB, BA):
        print("AB = BA")
    else:
        print("AB /= BA")

def prove_transpose():
    AB = np.dot(A, B)
    AB_T = np.transpose(AB)
    B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

    print("Transpose of AB:\n", AB_T)
    print("B^T * A^T:\n", B_T_A_T)
    if np.array_equal(AB_T, B_T_A_T):
        print("(AB)^T = B^T * A^T")
    else:
        print("(AB)^T /= B^T * A^T")

def main():
    print("Prove A.A^-1 = I")
    prove_A_inv()
    print("\n Prove AB /= BA")
    prove_AB_not_equal_BA()
    print("\n Prove (AB)^T = B^T * A^T")
    prove_transpose()

if __name__ == "__main__":
    main()

Prove A.A^-1 = I
A * A^-1 (Identity Matrix):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 Prove AB /= BA
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB /= BA

 Prove (AB)^T = B^T * A^T
Transpose of AB:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
(AB)^T = B^T * A^T


# Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT


In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution (x, y, z):")
print(X)


Solution (x, y, z):
[ 2.  1. -2.]


1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
#using python lists
import time
def list_addition():
    size = 1000000
    #creating 2 lists
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]

    #time taken
    start_time = time.time()
    result_list = [list1[i] + list2[i] for i in range(size)]
    end_time = time.time()

    return end_time - start_time
if __name__ == "__main__":
    list_time = list_addition()
    print(f"Time taken for element-wise addition using Python lists: {list_time:.6f} seconds")


Time taken for element-wise addition using Python lists: 0.087729 seconds


In [ ]:
#using numpy
import time
import numpy as np

def numpy_addition():
    size = 1000000

    array1 = np.arange(size)
    array2 = np.arange(size)

    #time taken
    start_time = time.time()
    result_array = array1 + array2
    end_time = time.time()

    return end_time - start_time

if __name__ == "__main__":
    numpy_time = numpy_addition()
    print(f"Time taken for element-wise addition using NumPy arrays: {numpy_time:.6f} seconds")


Time taken for element-wise addition using NumPy arrays: 0.004199 seconds


# 2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
#using python list
import time

def list_multiplication():
    size = 1000000
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]

    start_time = time.time()
    result_list = [list1[i] * list2[i] for i in range(size)]
    end_time = time.time()

    return end_time - start_time

if __name__ == "__main__":
    list_time = list_multiplication()
    print(f"Time taken for element-wise multiplication using Python lists: {list_time:.6f} seconds")


Time taken for element-wise multiplication using Python lists: 0.084606 seconds


In [ ]:
#using numpy
import time
import numpy as np

def numpy_multiplication():
    size = 1000000
    array1 = np.arange(size)
    array2 = np.arange(size)

    start_time = time.time()
    result_array = array1 * array2
    end_time = time.time()

    return end_time - start_time

if __name__ == "__main__":
    numpy_time = numpy_multiplication()
    print(f"Time taken for element-wise multiplication using NumPy arrays: {numpy_time:.6f} seconds")


Time taken for element-wise multiplication using NumPy arrays: 0.003656 seconds


# Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time

def list_dot_product():
    size = 1000000
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]

    start_time = time.time()
    dot_product = sum(list1[i] * list2[i] for i in range(size))
    end_time = time.time()

    return dot_product, end_time - start_time

if __name__ == "__main__":
    result, list_time = list_dot_product()
    print(f"Dot Product using Python lists: {result}")
    print(f"Time taken: {list_time:.6f} seconds")


Dot Product using Python lists: 333332833333500000
Time taken: 0.201136 seconds


In [ ]:
import time
import numpy as np

def numpy_dot_product():
    size = 1000000
    array1 = np.arange(size)
    array2 = np.arange(size)

    start_time = time.time()
    dot_product = np.dot(array1, array2)
    end_time = time.time()

    return dot_product, end_time - start_time

if __name__ == "__main__":
    result, numpy_time = numpy_dot_product()
    print(f"Dot Product using NumPy arrays: {result}")
    print(f"Time taken: {numpy_time:.6f} seconds")


Dot Product using NumPy arrays: 333332833333500000
Time taken: 0.001773 seconds


Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import random
import time

def generate_matrix(size):
    return [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]

def multiply_matrices_python(matrixA, matrixB, size):
    result_matrix = [[0 for _ in range(size)] for _ in range(size)]

    for row in range(size):
        for col in range(size):
            for k in range(size):
              result_matrix[row][col] += matrixA[row][k] * matrixB[k][col]

    return result_matrix

def measure_multiplication(size):
    matrixA = generate_matrix(size)
    matrixB = generate_matrix(size)

    start_time = time.time()
    multiply_matrices_python(matrixA, matrixB, size)
    end_time = time.time()

    print("Time taken using Python lists:", end_time - start_time, "seconds")

size = 1000
measure_multiplication(size)


Time taken using Python lists: 126.59576988220215 seconds


In [ ]:
import numpy as np
import time
size = 1000
def generate_matrix_numpy(size):
    return np.random.randint(1, 11, (size, size))

def multiply_matrices_numpy(matrixA, matrixB):
    return np.dot(matrixA, matrixB)

def measure_numpy_multiplication(size):
    matrixA = generate_matrix_numpy(size)
    matrixB = generate_matrix_numpy(size)

    start_time = time.time()
    multiply_matrices_numpy(matrixA, matrixB)
    end_time = time.time()

    print("Time taken using NumPy:", end_time - start_time, "seconds")


measure_numpy_multiplication(size)


Time taken using NumPy: 1.4590282440185547 seconds
